// modules/database.js — AUREX-9 v3.0 | Инициализация базы данных

async function initDB(db) {
  await db.query(`CREATE TABLE IF NOT EXISTS guild_settings (guild_id VARCHAR(32) NOT NULL, \`key\` VARCHAR(128) NOT NULL, value TEXT, PRIMARY KEY (guild_id, \`key\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS warnings (id INT AUTO_INCREMENT PRIMARY KEY, guild_id VARCHAR(32) NOT NULL, user VARCHAR(32) NOT NULL, count INT DEFAULT 0, UNIQUE KEY uniq_guild_user (guild_id, user)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS tickets (id INT AUTO_INCREMENT PRIMARY KEY, ticket_id VARCHAR(64) NOT NULL UNIQUE, guild_id VARCHAR(32) NOT NULL, channel_id VARCHAR(64), user_id VARCHAR(64), mod_id VARCHAR(64), status VARCHAR(32) DEFAULT 'open', category VARCHAR(64), priority VARCHAR(32) DEFAULT 'normal', subject TEXT, reason TEXT, closed_reason TEXT, closed_by VARCHAR(64), closed_at BIGINT, claimed_by VARCHAR(64), rating INT, created_at BIGINT, updated_at BIGINT, INDEX idx_guild (guild_id), INDEX idx_channel (channel_id), INDEX idx_status (status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS ticket_messages (id INT AUTO_INCREMENT PRIMARY KEY, ticket_id VARCHAR(64) NOT NULL, author_id VARCHAR(64), content TEXT, created_at BIGINT, INDEX idx_ticket (ticket_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS mod_stats (id INT AUTO_INCREMENT PRIMARY KEY, guild_id VARCHAR(32) NOT NULL, mod_id VARCHAR(64) NOT NULL, tickets_handled INT DEFAULT 0, warns_issued INT DEFAULT 0, mutes_issued INT DEFAULT 0, bans_issued INT DEFAULT 0, messages_deleted INT DEFAULT 0, avg_response_ms BIGINT DEFAULT 0, quality_score INT DEFAULT 0, last_active BIGINT, UNIQUE KEY uniq_guild_mod (guild_id, mod_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS bans_log (id INT AUTO_INCREMENT PRIMARY KEY, guild_id VARCHAR(32), moderator VARCHAR(64), user VARCHAR(64), created_at BIGINT, INDEX idx_guild_mod (guild_id, moderator)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS channel_delete_log (id INT AUTO_INCREMENT PRIMARY KEY, guild_id VARCHAR(32), executor VARCHAR(64), channel_name VARCHAR(256), created_at BIGINT, INDEX idx_guild_exec (guild_id, executor)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS aurex_training (id INT AUTO_INCREMENT PRIMARY KEY, guild_id VARCHAR(32), message TEXT, result_mat TINYINT DEFAULT 0, result_caps TINYINT DEFAULT 0, result_spam TINYINT DEFAULT 0, result_porn TINYINT DEFAULT 0, mod_decision TINYINT DEFAULT 0, moderator VARCHAR(64), created_at BIGINT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS aurex_weights (guild_id VARCHAR(32) NOT NULL, \`key\` VARCHAR(64) NOT NULL, value FLOAT DEFAULT 1.0, PRIMARY KEY (guild_id, \`key\`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS ai_blocks (guild_id VARCHAR(32) NOT NULL, user_id VARCHAR(32) NOT NULL, unblock_at BIGINT NOT NULL, reason TEXT, PRIMARY KEY (guild_id, user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS ai_daily_chat (guild_id VARCHAR(32) NOT NULL, user_id VARCHAR(32) NOT NULL, ts BIGINT NOT NULL, INDEX idx_user (guild_id, user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS eco_users (guild_id VARCHAR(32) NOT NULL, user_id VARCHAR(32) NOT NULL, coins INT DEFAULT 0, xp INT DEFAULT 0, level INT DEFAULT 1, messages INT DEFAULT 0, voice_mins INT DEFAULT 0, last_daily BIGINT DEFAULT 0, last_work BIGINT DEFAULT 0, PRIMARY KEY (guild_id, user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS eco_shop (id INT AUTO_INCREMENT PRIMARY KEY, guild_id VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, description TEXT, price INT DEFAULT 100, role_id VARCHAR(64), sort_order INT DEFAULT 0, INDEX idx_guild (guild_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS ticket_categories (id INT AUTO_INCREMENT PRIMARY KEY, guild_id VARCHAR(32) NOT NULL, name VARCHAR(64) NOT NULL, emoji VARCHAR(8) DEFAULT '🎫', description TEXT, role_id VARCHAR(64), sort_order INT DEFAULT 0, INDEX idx_guild (guild_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS mutes (guild_id VARCHAR(32) NOT NULL, user_id VARCHAR(32) NOT NULL, unmute_at BIGINT NOT NULL, reason TEXT, moderator VARCHAR(128), PRIMARY KEY (guild_id, user_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS mod_actions (id INT AUTO_INCREMENT PRIMARY KEY, guild_id VARCHAR(32) NOT NULL, mod_id VARCHAR(64), target_id VARCHAR(64), action VARCHAR(32), reason TEXT, duration BIGINT, created_at BIGINT, INDEX idx_guild (guild_id), INDEX idx_mod (guild_id, mod_id), INDEX idx_target (guild_id, target_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  await db.query(`CREATE TABLE IF NOT EXISTS server_rules (id INT AUTO_INCREMENT PRIMARY KEY, guild_id VARCHAR(32) NOT NULL, type VARCHAR(32) DEFAULT 'server', title VARCHAR(256), content TEXT, sort_order INT DEFAULT 0, INDEX idx_guild (guild_id, type)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);
  console.log("✅ AUREX-9 v3.0 — таблицы инициализированы");
}

module.exports = { initDB };
